--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mongo-express
  name: mongo-express
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo-express
  template: 
    metadata: 
      labels: 
        app: mongo-express
      spec: 
        containers: 
          - 
            env: 
              - 
                name: ME_CONFIG_MONGODB_ADMINUSERNAME
                valueFrom: 
                  secretKeyRef: 
                    key: mongo-root-username
                    name: mongodb-secret
              - 
                name: ME_CONFIG_MONGODB_ADMINPASSWORD
                valueFrom: 
                  secretKeyRef: 
                    key: mongo-root-password
                    name: mongodb-secret
              - 
                name: ME_CONFIG_MONGODB_SERVER
                valueFrom: 
                  ConfigMapKeyRef: 
                    key: database_url
                    name: mongodb-configmap
            image: mongo-express
            name: mongo-application
            ports: 
              - 
                containerPort: 8081
